name: Rust

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive
    - uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        override: true
    - name: Install alsa and udev
      run: |
        sudo apt update
        sudo apt install -y build-essential ninja-build libasound2-dev libudev-dev libsdl2-dev cmake clang libclang-dev
    - name: Build
      run: cd raylib && cargo build --verbose --features nobuild
